---
title: "Con"
author: "Connor Logue"
date: "2024-12-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Libraries
```{r}
library(dplyr)
library(glmnet)
library(car)
library(nestedcv)
library(xtable)
library(corrplot)
```

### Data
```{r}
data = read.csv("combined.csv", header = TRUE)
data
```

### Cleansing
```{r}
data$Yrs_in_NHL <- 2016 - data$DftYr
data$A = data$A1 + data$A2
data$Salary_log_corrected <- data$Salary_log

data$GF[is.na(data$GF)] <- median(data$GF, na.rm=TRUE)
data$GA[is.na(data$GA)] <- median(data$GA, na.rm=TRUE)
data$iSF[is.na(data$iSF)] <- median(data$iSF, na.rm=TRUE)
data$Yrs_in_NHL[is.na(data$Yrs_in_NHL)] <- 0
data$iHA[is.na(data$iHA)] <- median(data$iHA, na.rm=TRUE)

data <- data[data$Yrs_in_NHL > 3,]
data <- data[data$Is_Offense == 1,]
```


### EDA | Pairwise Plots
```{r, fig.height=7.5}
plot(data$TOI, data$Salary_log)
lines(lowess(data$TOI, data$Salary_log), col=2)
```

### OLS
```{r}
data$TOI_c   <- scale(data$TOI, scale = FALSE)
data$TOI_c2  <- data$TOI_c^2
bedrock <- lm(Salary_log ~ G + A + GF + GA + plus_mins + TOI_c + TOI_c2 + iSF + Yrs_in_NHL + Ht + Wt + iHF + iHA + iBLK + PIM + GP, data = data)

summary(bedrock)
mean(vif(bedrock))
```

```{r}
vif(bedrock)
mean(vif(bedrock))

```


```{r, fig.height = 10}
par(mfrow = c(2,2))
plot(bedrock)
```


### Print
```{r}
#xtable(summary(bedrock_poly), digits = 3)
```

```{r}
#coef <- data.frame(coef(bedrock_poly))
#coef$expo_coef = (exp(coef$coef.bedrock_poly) - 1) * 1000000
#coef_sub <- subset(coef, select = expo_coef)
#xtable(coef_sub, digits = 0)
```


```{r}
#confidence <- data.frame(confint(bedrock_poly, level = 0.95))
#confidence$expo_lower = (exp(confidence$X2.5..) - 1) * 1000000
#confidence$expo_upper = (exp(confidence$X97.5..) - 1) * 1000000
#conf_sub <- subset(confidence, select = c(expo_lower, expo_upper))
#xtable(conf_sub, digits = 0)
```


### EDA | Simple Linear Regression
```{r}
uni <- lm(Salary_log ~ GP, data = data)
summary(uni)
```

### EDA | Correlation Plot
```{r, fig.width=10, fig.height=10}
pairwise <- subset(data, select = c(G, A, GF, GA, plus_mins, TOI, iSF, Yrs_in_NHL, Ht, Wt, iHF, iHA, iBLK, PIM, GP))
M = cor(pairwise)
corrplot(M, method = 'number')
```

### Elastic Net
```{R}
X         <- model.matrix(Salary_log ~ G + A + GF + GA + plus_mins + Yrs_in_NHL + TOI_c + TOI_c2 + iSF + Ht + Wt + iHF + iHA + iBLK + Grit + GP -1, data = data)
Y         <- data$Salary_log


elastic   <- glmnet(x = X, y = Y, family = "gaussian", intercept = TRUE, alpha = 0.5)
plot(elastic, xvar = "lambda", label = TRUE)
```

```{r}
elastic_cv   <- cv.glmnet(x = X, y = Y, family = "gaussian", alpha = 0.5, ype.measure = "mse", nfolds = nrow(data), grouped = FALSE)
coef(elastic_cv) 
```

```{r}
baseline <- lm(Salary_log ~ A + GF + plus_mins + Yrs_in_NHL + TOI_c + TOI_c2 +  iSF + Wt + iHF + iBLK + GP, data = data)
summary(baseline)
```


```{r}
vif(baseline)
mean(vif(baseline))
```


### Cross-Nested Validation
```{r}
library(glmnet)
library(nestedcv)
X         <- model.matrix(Salary_log ~ A + GF + plus_mins + TOI + iSF + Yrs_in_NHL + Wt + GP -1, data = scaled_data)
Y         <- scaled_data$Salary_log


test <- nestcv.glmnet(x = X, y = Y, family = "gaussian", alphaSet = seq(0, 0.3, 0.1), type.measure = "mse", n_outer_folds = 10, n_inner_folds = 10, grouped = FALSE)

plot(test$outer_result[[1]]$cvafit)

```
```{R}
summary(test)
```









### Penalized Regression



```{R}

group1 <- rep(1:20, each=5)
ml <- gglasso(x=bardet$x, y=bardet$y, group=group1, loss="ls")

```


```{R}

#X         <- model.matrix(Salary_log ~ G + A + GF + GA + plus_mins + TOI + TOI_2 + iSF + Yrs_in_NHL + Ht + Wt + iHF + iHA + iBLK + PIM + GP -1, data = scaled_data)
X <- subset(scaled_data, select = c(G, A, GF, GA ))
Y         <- scaled_data$Salary_log

group1 <- rep(1:2, each = 2)




fit_ls <- gglasso(x = test$X, y = test$Y, group = group1, loss = "ls")
```












```{r}
library(psych)
describe(data$Salary)
```
```{r}
hist(data$Salary)
```



```{r, fig.height=10}
plot(EDA[, 1:7])
```
